global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-mobitor'

rule_files:


scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['manager-001:9100','worker-001:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['docker-manager-001:8080','docker-worker-001:8080']