global:
  scrape_interval: 5s
  evaluation_interval: 5s
  
  
  external_labels:
    monitor: 'Monitoring'

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor' 
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  
  - job_name: 'Docker'
    static_configs:
      - targets: ['YOUR_IP_HERE:9323'] # place Your IP.

  - job_name: blackbox # To get metrics about the exporter itself.
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox_exporter:9115

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx, icmp]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - https://noorbala7418.ir # Target to probe with https.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
