modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      # valid_http_versions: ["HTTP/1.1", "HTTP/2"] # this option had a problem. do not enbale it.
      valid_status_codes: [200]  # Defaults to 2xx
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      # fail_if_not_ssl: false
      fail_if_body_matches_regexp:
        - "Could not connect to database"
      # tls_config:
        # insecure_skip_verify: true

  icmp:
    prober: icmp
    timeout: 2s
